<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1373" started-at="2014-02-04T19:10:49Z" finished-at="2014-02-04T19:10:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1373" started-at="2014-02-04T19:10:49Z" finished-at="2014-02-04T19:10:50Z">
      <class name="adminloginTest">
        <test-method status="FAIL" signature="AdminLogin(org.testng.ITestContext)[pri:0, instance:adminloginTest@da9e2a]" name="AdminLogin" is-config="true" duration-ms="0" started-at="2014-02-04T13:10:49Z" finished-at="2014-02-04T13:10:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1d41dc3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Can't start selenium server]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Can't start selenium server
	at adminloginTest.AdminLogin(adminloginTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.net.BindException: Selenium is already running on port 4444. Or some other service is.
	at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:491)
	at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:300)
	at adminloginTest.AdminLogin(adminloginTest.java:34)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminLogin -->
        <test-method status="SKIP" signature="AdminLogin(org.testng.ITestContext)[pri:0, instance:adminloginTest@da9e2a]" name="AdminLogin" duration-ms="1" started-at="2014-02-04T13:10:50Z" finished-at="2014-02-04T13:10:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1d41dc3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminLogin -->
      </class> <!-- adminloginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
